# Generated by Django 5.2.1 on 2025-05-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactlist_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='phone_number',
        ),
    ]
