# Generated by Django 5.2.1 on 2025-05-23 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='private_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
