# Generated by Django 5.2.1 on 2025-05-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userprofile_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
